version: '3.7'

services:
  server-node:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: server-node
    ports:
      - "3030:3030"
    environment:
    - REDIS_URL=redis://redis
    links:
    - redis
    depends_on:
            - web-server

  server-node2:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: server-node2
    environment:
    - REDIS_URL=redis://redis
    links:
    - redis
    depends_on:
            - web-server

  redis:
    image: redis:latest
    container_name: redis
    expose:
            - 6379
    volumes:
      - ./data:/data

  web-server:
    image: nginx:mainline-alpine
    container_name: web-server
    volumes:
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        - "./nginx/nginx_params.conf:/etc/nginx/nginx.conf"
    ports:
        - "80:80"